---

- hosts: all
  become: yes
  tasks:
  - name: apt update
    apt:
      update_cache: yes
      cache_valid_time: 3600
      force_apt_get: yes

  - name: apt -y upgrade ; apt -y dist-upgrade ; apt -y autoremove ; apt -y autoclean
    apt:
      update_cache: yes
#      upgrade: dist
      cache_valid_time: 3600
      force_apt_get: yes
      autoremove: yes
      autoclean: yes

  - name: Install packages
    apt:
      name:
      - apache2
      - curl
      - git
      - locate
      - net-tools
      - socat
      - wget
      state: latest

  - name: Install Apache modules
    shell: |
      a2enmod headers proxy proxy_html proxy_http rewrite ssl

  - name: Start Apache
    service:
      name: apache2
      state: started

  - name: Change Apache config to allow for mod-rewrite
    ansible.builtin.replace:
      path: /etc/apache2/apache2.conf
      after: '<Directory /var/www/>'
      before: '</Directory>'
      regexp: ^\tAllowOverride None$
      replace: '\tAllowOverride All'

  - name: Restart the Apache service
    service:
      name: apache2
      state: restarted
