name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build:
        - name: sn0int
          file: Dockerfile
        - name: registry
          file: sn0int-registry/Dockerfile

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: DOCKER_BUILDKIT=1 docker build -t ${{ matrix.build.name }} -f ${{ matrix.build.file }} .
    - name: Test the Docker image
      run: docker run --rm ${{ matrix.build.name }} --help

    - name: Show Docker images
      run: docker images
